name:                lichess-flashcards
version:             0.1.0.0
github:              "githubuser/lichess-flashcards"
license:             BSD3
author:              "Anthony Green"
maintainer:          "argreen@umich.edu"
copyright:           "Anthony Green"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            A library for downloading lichess games and making interactive flashcards out of them.
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/lichess-flashcards#readme>

dependencies:
- base >= 4.7 && < 5
- http-conduit >= 2.3 && < 2.4
- bytestring >= 0.10 && < 0.11
- aeson >= 1.3 && < 1.5
- bytestring >= 0.10

library:
  source-dirs: src

executables:
  lichess-flashcards-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - lichess-flashcards

tests:
  lichess-flashcards-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - lichess-flashcards
